name: Backend CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, backend]   # must match your runner’s label
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test backend runner
        run: echo "Running on backend runner"

